Virtual_lawyer/fyp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('virtual_lawyer.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Virtual_lawyer/virtual_lawyer/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views
from . import views as user_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


# ......




app_name = 'virtual_lawyer'

urlpatterns = [
    path('', user_views.index, name='Home'),
    path('about/', user_views.about, name='about'),
    path('chatbot/', user_views.chatbot, name= 'chatbot'),
    path('lawyers/', user_views.getLawyers, name= 'lawyers'),
    
    path('getChat/', views.getChat, name= 'getChat'),

    path('register', views.register, name="register"),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    path('login', auth_views.LoginView.as_view(template_name='virtual_lawyer/login.html'), name="login"),
    path('logout', auth_views.LogoutView.as_view(template_name='virtual_lawyer/index.html'), name="logout"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Virtual_lawyer/virtual_lawyer/models.py
from django.db import models
from chatterbot import ChatBot
from chatterbot.ext.django_chatterbot import settings
from chatterbot.trainers import ChatterBotCorpusTrainer
from django.apps import apps


#for integration
import numpy as np
from datetime import datetime
import click
from os import path
import tensorflow as tf
from tensorflow.python.layers import core as layers_core
from tensorflow.contrib.tensorboard.plugins import projector
from os import path

from chatbot.vocabulary import Vocabulary
import chatbot.general_utils
import chatbot.chat_command_handler as chat_command_handler
from chatbot.chat_settings import ChatSettings

#end



class Chatbot(models.Model):
    bot = None
    settings = None
    model_dir, hparams, checkpoint = chatbot.general_utils.initialize_session_server()
    @classmethod
    def get_ChatBot(self):

        if self.bot is None:
            #Read the hyperparameters and configure paths
            model_dir, hparams, checkpoint = chatbot.general_utils.initialize_session_server()

            #Load the vocabulary
            print()
            print ("Loading vocabulary...")
            if hparams.model_hparams.share_embedding:
                shared_vocab_filepath = path.join(model_dir, Vocabulary.SHARED_VOCAB_FILENAME)
                input_vocabulary = Vocabulary.load(shared_vocab_filepath)
                output_vocabulary = input_vocabulary
            else:
                input_vocab_filepath = path.join(model_dir, Vocabulary.INPUT_VOCAB_FILENAME)
                input_vocabulary = Vocabulary.load(input_vocab_filepath)
                output_vocab_filepath = path.join(model_dir, Vocabulary.OUTPUT_VOCAB_FILENAME)
                output_vocabulary = Vocabulary.load(output_vocab_filepath)

            #Create the model
            print ("Initializing model...")
            print()
            with ChatbotModel(mode = "infer",
                            model_hparams = hparams.model_hparams,
                            input_vocabulary = input_vocabulary,
                            output_vocabulary = output_vocabulary,
                            model_dir = model_dir) as model:

                #Load the weights
                print()
                print ("Loading model weights...")
                model.load(checkpoint)

                # Setting up the chat
                chat_settings = ChatSettings(hparams.model_hparams, hparams.inference_hparams)
                self.settings = chat_settings
                chat_command_handler.print_commands()
                self.bot = model
        return self.bot, self.settings

    @classmethod
    def get_bot_response(self, question, model, chat_settings):
        print ("Entered in bot response")
        chatlog_filepath = path.join(self.model_dir, "chat_logs", "web_chatlog_{0}.txt".format(datetime.today().strftime("%Y%m%d")))
        is_command, terminate_chat, _ = chat_command_handler.handle_command(question, model, chat_settings)
        if terminate_chat:
            answer = "[Can't terminate from http request]"
        elif is_command:
            answer = "[Command processed]"
        else:
            #If it is not a command (it is a question), pass it on to the chatbot model to get the answer
            _, answer = model.chat(question, chat_settings)
            print("printing answer")
            print(answer)
            if chat_settings.inference_hparams.log_chat:
                chat_command_handler.append_to_chatlog(chatlog_filepath, question, answer)
        return answer




class ChatbotModel(object):
    """Seq2Seq chatbot model class.

    This class encapsulates all interaction with TensorFlow. Users of this class need not be aware of the dependency on TF.
    This abstraction allows for future use of alternative DL libraries* by writing ChatbotModel implementations for them
    without the calling code needing to change.

    This class implementation was influenced by studying the TensorFlow Neural Machine Translation (NMT) tutorial:
        - https://www.tensorflow.org/tutorials/seq2seq
    These files were helpful in understanding the seq2seq implementation:
        - https://github.com/tensorflow/nmt/blob/master/nmt/model.py
        - https://github.com/tensorflow/nmt/blob/master/nmt/model_helper.py
        - https://github.com/tensorflow/nmt/blob/master/nmt/attention_model.py

    Although the code in this implementation is original, there are some similarities with the NMT tutorial in certain places.
    """
    
    def __init__(self,
                 mode,
                 model_hparams,
                 input_vocabulary,
                 output_vocabulary,
                 model_dir):
        """Create the Seq2Seq chatbot model.
        
        Args:
            mode: "train" or "infer"
            
            model_hparams: parameters which determine the architecture and complexity of the model.
                See hparams.py for in-depth comments.
            
            input_vocabulary: the input vocabulary. Each word in this vocabulary gets its own vector
                in the encoder embedding matrix.
                
            output_vocabulary: the output vocabulary. Each word in this vocabulary gets its own vector
                in the decoder embedding matrix.
                
            model_dir: the directory to output model summaries and load / save checkpoints.
        """
        self.mode = mode
        self.model_hparams = model_hparams
        self.input_vocabulary = input_vocabulary
        self.output_vocabulary = output_vocabulary
        self.model_dir = model_dir

        #Validate arguments
        if self.model_hparams.share_embedding and self.input_vocabulary.size() != self.output_vocabulary.size():
            raise ValueError("Cannot share embedding matrices when the input and output vocabulary sizes are different.")
        
        if self.model_hparams.share_embedding and self.model_hparams.encoder_embedding_size != self.model_hparams.decoder_embedding_size:
            raise ValueError("Cannot share embedding matrices when the encoder and decoder embedding sizes are different.")

        if self.input_vocabulary.external_embeddings is not None and self.input_vocabulary.external_embeddings.shape[1] != self.model_hparams.encoder_embedding_size:
            raise ValueError("Cannot use external embeddings with vector size {0} for the encoder when the hparams encoder embedding size is {1}".format(self.input_vocabulary.external_embeddings.shape[1],
                                                                                                                                                         self.model_hparams.encoder_embedding_size))
        if self.output_vocabulary.external_embeddings is not None and self.output_vocabulary.external_embeddings.shape[1] != self.model_hparams.decoder_embedding_size:
            raise ValueError("Cannot use external embeddings with vector size {0} for the decoder when the hparams decoder embedding size is {1}".format(self.output_vocabulary.external_embeddings.shape[1],
                                                                                                                                                         self.model_hparams.decoder_embedding_size))
                                                                                                                                            
        tf.contrib.learn.ModeKeys.validate(self.mode)
        
        if self.mode == tf.contrib.learn.ModeKeys.TRAIN or self.model_hparams.beam_width is None:
            self.beam_width = 0
        else:
            self.beam_width = self.model_hparams.beam_width
        
        #Reset the default TF graph
        tf.reset_default_graph()
        
        #Define general model inputs
        self.inputs = tf.placeholder(tf.int32, [None, None], name = "inputs")
        self.input_sequence_length = tf.placeholder(tf.int32, [None], name = "input_sequence_length")
        
        #Build model
        initializer_feed_dict = {}
        if self.mode == tf.contrib.learn.ModeKeys.TRAIN:
            #Define training model inputs
            self.targets = tf.placeholder(tf.int32, [None, None], name = "targets")
            self.target_sequence_length = tf.placeholder(tf.int32, [None], name = "target_sequence_length")
            self.learning_rate = tf.placeholder(tf.float32, name= "learning_rate")
            self.keep_prob = tf.placeholder(tf.float32, name = "keep_prob")
            if self.input_vocabulary.external_embeddings is not None:
                self.input_external_embeddings = tf.placeholder(tf.float32, 
                                shape = self.input_vocabulary.external_embeddings.shape, 
                                name = "input_external_embeddings")
                initializer_feed_dict[self.input_external_embeddings] = self.input_vocabulary.external_embeddings
            if self.output_vocabulary.external_embeddings is not None and not self.model_hparams.share_embedding:
                self.output_external_embeddings = tf.placeholder(tf.float32, 
                                shape = self.output_vocabulary.external_embeddings.shape,
                                name = "output_external_embeddings")
                initializer_feed_dict[self.output_external_embeddings] = self.output_vocabulary.external_embeddings
            
            self.loss, self.training_step = self._build_model()
        
        elif self.mode == tf.contrib.learn.ModeKeys.INFER:
            #Define inference model inputs
            self.max_output_sequence_length = tf.placeholder(tf.int32, [], name="max_output_sequence_length")
            self.beam_length_penalty_weight = tf.placeholder(tf.float32, name = "beam_length_penalty_weight")
            self.sampling_temperature = tf.placeholder(tf.float32, name = "sampling_temperature")
            

Virtual_lawyer/virtual_lawyer/forms.py
from django.forms.widgets import HiddenInput
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm


class UserRegisrationForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField()
    last_name = forms.CharField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username',
                  'email', 'password1', 'password2']

Virtual_lawyer/virtual_lawyer/views.py
from django.contrib.auth.models import User
from .forms import UserRegisrationForm

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from django.views.generic.base import TemplateView
from django.views.generic import View
from django.http import JsonResponse,HttpResponse
from .models import Chatbot,Lawyer
from django.views.decorators.csrf import csrf_exempt

from django.contrib.sites.shortcuts import get_current_site  
from .tokens import account_activation_token 
from django.utils.encoding import force_bytes, force_text  
from django.contrib.auth.models import User  
from django.core.mail import EmailMessage
from django.core.mail import EmailMultiAlternatives
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode  
from django.template.loader import render_to_string


# Create your views here.
def index(request):
    return render(request, 'virtual_lawyer/index.html')

def about(request):
    return render(request,'virtual_lawyer/about.html')
@login_required
@csrf_exempt
def chatbot(request):
    return render(request, 'virtual_lawyer/chatbot.html')
@csrf_exempt
def getChat(request):
    # bot = Chatbot()
    myBot, mySettings = Chatbot.get_ChatBot()
    botResponse = ''
    if request.method == "POST":
        User = request.POST["talk"]
        botResponse = myBot.get_response(User,myBot, mySettings)
        print(botResponse)
        print("printing bot response***************************************")
        return HttpResponse(botResponse)
    else:
        return HttpResponse(botResponse)



def register(request): 
    if request.method == 'POST':  
        form = UserRegisrationForm(request.POST)  
        # print(form.errors.as_data())  
        if form.is_valid():  
            user = form.save(commit=False)  
            user.is_active = False  
            user.save()  
            current_site = get_current_site(request)  
            mail_subject = 'Activate your account.'  
            msg = {                
                'user': user,  
                'domain': current_site.domain,  
                'uid': urlsafe_base64_encode(force_bytes(user.id)),  
                'token': account_activation_token.make_token(user),
                }
            message = render_to_string('virtual_lawyer/activate.html',{  
                'user': user,  
                'domain': current_site.domain,  
                'uid': urlsafe_base64_encode(force_bytes(user.id)),  
                'token': account_activation_token.make_token(user),  
            })
            to_email = form.cleaned_data.get('email')  
            print(to_email)
            email = EmailMultiAlternatives(  
                mail_subject, message, to=[to_email]  
            )  
            html_body = render_to_string("virtual_lawyer/activate.html", msg)
            email.attach_alternative(html_body, "text/html")
            email.send()  
            return render(request, 'virtual_lawyer/confirmationPage.html')
            # return HttpResponse('Please confirm your email address to complete the registration') 
  
    else:  
        form = UserRegisrationForm()  
    return render(request, 'virtual_lawyer/register.html', {'form': form})


def activate(request, uidb64, token):  
        try:  
            uid = force_text(urlsafe_base64_decode(uidb64))  
            user = User.objects.get(id=uid)  
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):  
            user = None  
        if user is not None and account_activation_token.check_token(user, token):  
            user.is_active = True  
            user.save()  
            return render(request, 'virtual_lawyer/accountActivationConfirmed.html')
            # return HttpResponse('Thank you for your email confirmation. Now you can login your account.')  
        else:  
            return HttpResponse('Activation link is invalid!')

def getLawyers(request):
    all_lawyers = Lawyer.objects.all()
    return render(request, 'virtual_lawyer/lawyers.html', {'all_lawyers': all_lawyers})




#integration of new model





#end

Virtual_lawyer/virtual_lawyer/templates/virtual_lawyer/about.html
{% extends "virtual_lawyer/base.html" %}
{% block content %}
{% load static %}
        <!-- bradcam_area_start -->
        <div class="slider_area " >
            <div class="single_slider d-flex align-items-center justify-content-center slider_bg_1">
                <div class="container">
                    <div class="row align-items-center justify-content-center">
        
                        <div class="col-xl-12 col-md-12">
                            <div class="slider_info" style="text-align: center">
                                <h3>About Us </h3>
                            </div>
                        </div>
        
                    </div>
                </div>
            </div>
        </div>
        <!-- bradcam_area_end -->

  <!-- about_area_start -->
<div class="about_area">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-6">
                    <div class="single_about_info">
                        <h3>Dealing 15 types <br>
                            of Legal Cases</h3>
                        <p>Virtual Legal Advisor deals with different kinds of cases including civil rights and
                            criminal issues. The virtual system understands the user's problem and suggests him/her
                            a solution for the problem. </p>
                        <a href="{% url 'virtual_lawyer:chatbot' %}" class="boxed_btn">Start Chat</a>
                    </div>
                </div>
                <div class="col-xl-6 offset-xl-1 col-lg-6">
                    <div class="about_tutorials">
                        <div class="courses">
                            <div class="inner_courses">
                                <div class="text_info">
                                    <span>5+</span>
                                    <p> Case Domains</p>
                                </div>
                            </div>
                        </div>
                        <div class="courses-blue">
                            <div class="inner_courses">
                                <div class="text_info">
                                    <span>Online</span>
                                    <p>System</p>
                                </div>
    
                            </div>
                        </div>
                        <div class="courses-sky">
                            <div class="inner_courses">
                                <div class="text_info">
                                    <span>Free</span>
                                    <p>Legal Advice</p>
                                </div>
    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- about_area_end -->
    <!--
    <div class="about_area">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-6">
                        <div class="single_about_info">
                            <h3>Members: </h3>  
                        </div>
                    </div>
                </div>
            </div>
    </div>
    -->
    
    

    <!-- our_team_member_start -->
    <!-- <div class="our_team_member">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="single_team">
                        <div class="thumb">
                            <img src="img/team/1.png" alt="">
                            <div class="social_link">
                                <a href="#"><i class="fa fa-envelope"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                            </div>
                        </div>
                        <div class="master_name text-center">
                            <h3>Hunia Fatima </h3>
                            <p>...</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="single_team">
                        <div class="thumb">
                            <img src="img/team/2.png" alt="">
                            <div class="social_link">
                                <a href="#"><i class="fa fa-envelope"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                            </div>
                        </div>
                        <div class="master_name text-center">
                            <h3>Mubasher Ahmad</h3>
                            <p>...</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="single_team">
                        <div class="thumb">
                            <img src="img/team/3.png" alt="">
                            <div class="social_link">
                                <a href="#"><i class="fa fa-envelope"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                            </div>
                        </div>
                        <div class="master_name text-center">
                            <h3>Qaim Ali</h3>
                            <p>...</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="single_team">
                        <div class="thumb">
                            <img src="img/team/4.png" alt="">
                            <div class="social_link">
                                <a href="#"><i class="fa fa-envelope"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                            </div>
                        </div>
                        <div class="master_name text-center">
                            <h3>Sanan Hassan</h3>
                            <p>...</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> -->
    <!-- our_team_member_end -->

<!-- testimonial_area_start -->
<div class="testimonial_area testimonial_bg_1 overlay">
        <div class="testmonial_active owl-carousel">
            <div class="single_testmoial">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="testmonial_text text-center">
                                
                                <p>
                                    The law was made for one thing alone, for the exploitation of those who don't understand it. <br>
                                    alleviate human suffering. So let's know about our rights"
    
                                </p>
                                <span>- BERTOLT BRECHT</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="single_testmoial">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="testmonial_text text-center">
                                
                                <p>
                                    "The precepts of the law may be comprehended under these three points: <br> to live honestly, to hurt no man willfully, and to render every man his due carefully."
                                </p>
                                <span>- ARISTOTLE</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- testimonial_area_end -->
    
<!-- our_courses_start -->
<div class="our_courses">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="section_title text-center mb-100">
                        <h3>Our System Offers</h3>
                        <p>Along with providing the legal solution. Our system offers the following
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-3 col-md-6 col-lg-6">
                    <div class="single_course text-center">
                        <div class="icon">
                            <i class="flaticon-art-and-design"></i>
                        </div>
                        <h3>Legal Solution</h3>
                        <p>
                            At the end of the conversation with the chatbot. Our system provides legal 
                            solution to the user's case.
                        </p>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-6">
                    <div class="single_course text-center">
                        <div class="icon blue">
                            <i class="flaticon-business-and-finance"></i>
                        </div>
                        <h3>Law Clauses</h3>
                        <p>
                            Along with the legal solution, our system provides legal clauses applicable
                            to the provided solution.
                        </p>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-6">
                    <div class="single_course text-center">
                        <div class="icon">
                            <i class="flaticon-premium"></i>
                        </div>
                        <h3>Case Documentation</h3>
                        <p>
                            Case with its complete details is documented and provided to the user. It would be easy to
                            for lawyer to study the case. 
                        </p>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-6">
                    <div class="single_course text-center">
                        <div class="icon gradient">
                            <i class="flaticon-crown"></i>
                        </div>
                        <h3>Lawyers' List</h3>
                        <p>
                           List of well reputed and related field lawyers, is provided at the end of the 
                           session is provided to the user.
                           
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- our_courses_end -->
    

<!-- subscribe_newsletter_Start -->
<!-- <div class="subscribe_newsletter">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 col-lg-6">
                    <div class="newsletter_text">
                        <h3>Subscribe Newsletter</h3>
                        <p>Subscribe to our newsletter to get notified with the advancement in the Virtual Legal Advisor.</p>
                    </div>
                </div>
                <div class="col-xl-5 offset-xl-1 col-lg-6">
                    <div class="newsletter_form">
                        <h4>Subscribe here</h4>
                        <form action="#" class="newsletter_form">
                            <input type="text" placeholder="Enter your mail">
                            <button type="submit">Sign Up</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div> -->
    <!-- subscribe_newsletter_end -->
    {% endblock %}

Virtual_lawyer/virtual_lawyer/templates/virtual_lawyer/login.html
{% extends 'virtual_lawyer/base.html'%}


{% block content %}

{% load static %}
<div class="slider_area " >
    <div class="single_slider d-flex align-items-center justify-content-center slider_bg_2">
        <div class="container">
            <div class="row align-items-center justify-content-center">

                <div class="col-xl-12 col-md-12">
                    <div class="slider_info" style="text-align: center">
                        <h3>Login </h3>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{%load crispy_forms_tags%}
<div class="content-section" style="margin-top:100px">
    <div class="col-sm-6" style="margin-left:25%">
        <form method="POST" action="login">
            {% csrf_token %}
            {{form|crispy}}
            <button class=" btn btn-outline-info" type="submit">Sign In</button>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an Account?<a href="{%url 'virtual_lawyer:register'%}">SignUp</a>
            </small>
        </div>
    </div>
</div>

{% endblock content %}

Virtual_lawyer/virtual_lawyer/templates/virtual_lawyer/logout.html
{% extends 'virtual_lawyer/base.html'%}
{% block content %}
<div class="content-section" style="margin-top:50px">
    <div class="col-sm-6" style="margin-left:25%">
        <h3>You have been Logged Out!</h3>
        <div class="border-top pt-3">
            <small class="text-muted">
               Want to Login?<a href="{%url 'virtual_lawyer:login'%}">Sign In</a>
            </small>
        </div>
    </div>
</div>

{% endblock content %}

Virtual_lawyer/virtual_lawyer/templates/virtual_lawyer/register.html
{% extends 'virtual_lawyer/base.html'%}
{%load crispy_forms_tags%}
{% block content %}
<div class="slider_area " >
    <div class="single_slider d-flex align-items-center justify-content-center slider_bg_2">
        <div class="container">
            <div class="row align-items-center justify-content-center">

                <div class="col-xl-12 col-md-12">
                    <div class="slider_info" style="text-align: center">
                        <h3>Register </h3>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<div class="content-section" style="margin-top:100px">
    <div class="col-sm-6"style ="margin-left:25%">
        <form method="POST" action='register'>
            {% csrf_token %}
            {{form|crispy}}
            <button class=" btn btn-outline-info" type="submit">Sign Up</button>
        </form>
        <div class="border-top pt-5" style="margin-top:30px" >
            <small class="text-muted">
                Already  an Account?  <b><a href="{%url 'virtual_lawyer:login'%}">Sign In</a></b>
            </small>
        </div>
    </div>
</div>

{% endblock content %}